
--
-- Dumping data for table `pluginwizard_configuration_key`
--
INSERT INTO pluginwizard_configuration_key (id_key, key_description, key_value) VALUES (1,'plugin_version_number','1.0.0');
INSERT INTO pluginwizard_configuration_key (id_key, key_description, key_value) VALUES (2,'pom_parent_version','2.29');
INSERT INTO pluginwizard_configuration_key (id_key, key_description, key_value) VALUES (3,'pom_model_version','4.0.0');
INSERT INTO pluginwizard_configuration_key (id_key, key_description, key_value) VALUES (4,'pom_dependencies_core_version','[4.0.0,6.0.0-SNAPSHOT)');

--
-- Dumping data for table `pluginwizard_localization_key`
--
INSERT INTO pluginwizard_localization_key (id_key, key_name, english_locale, french_locale ) VALUES ( 1 , "plugin.provider", "<plugin's provider to define>","<fournisseur du plugin à compléter>" );
INSERT INTO pluginwizard_localization_key (id_key, key_name, english_locale, french_locale ) VALUES ( 2 , "plugin.description", "<plugin's decription to define>", "<description du plugin à compléter>" );
INSERT INTO pluginwizard_localization_key (id_key, key_name, english_locale, french_locale ) VALUES ( 3 , "buttonValidate", "Validate" , "Valider" );
INSERT INTO pluginwizard_localization_key (id_key, key_name, english_locale, french_locale ) VALUES ( 4 , "pageTitle", "Page's title","Titre de la page" );
INSERT INTO pluginwizard_localization_key (id_key, key_name, english_locale, french_locale ) VALUES ( 5 , "tableLabel", "List of elements", "Liste des éléments" );
INSERT INTO pluginwizard_localization_key (id_key, key_name, english_locale, french_locale ) VALUES ( 6 , "name", "<Feature generated by PluginWizard>","<Fonctionnalité générée par PluginWizard>" );
INSERT INTO pluginwizard_localization_key (id_key, key_name, english_locale, french_locale ) VALUES ( 7 , "description", "<Description of the Feature generated by PluginWizard>", "<Description de la fonctionnalité générée par PluginWizard>" );

--
-- Dumping data for table `pluginwizard_plugin_attribute_type`
--
INSERT INTO pluginwizard_plugin_attribute_type (attribute_type_id, attribute_type_name) VALUES (1,'int');
INSERT INTO pluginwizard_plugin_attribute_type (attribute_type_id, attribute_type_name) VALUES (2,'String');

 